'use client';
import {useState} from 'react';
import {Folder,FolderOpen,FolderPlus,Star,Pin,Search,LockKeyhole,Unlock,ChevronDown,ChevronRight,MoreHorizontal,Plus,ListFilter,Menu,FileText,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Checkbox} from '@/components/ui/checkbox';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem,DropdownMenuLabel,DropdownMenuSeparator} from '@/components/ui/dropdown-menu';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Collapsible,CollapsibleTrigger,CollapsibleContent} from '@/components/ui/collapsible';
import {Table,TableHeader,TableHead,TableRow,TableBody,TableCell} from '@/components/ui/table';
import type {Row} from '@/lib/model';

type Props={me:Row;files:Row[];items:Row[];users:Row[];groups:Row[];companyName:(id:string)=>string;onOpen:(f:Row)=>void;onNew:()=>void;call:(a:string,b?:any,close?:boolean)=>Promise<any>;folderMode:boolean};
export default function FileBrowser({me,files,items,users,groups,companyName,onOpen,onNew,call,folderMode}:Props){
 const prefs=me.workspacePrefs;
 const [view,setView]=useState('all'),[selected,setSelected]=useState<string[]>([]),[folder,setFolder]=useState('all');
 const [query,setQuery]=useState(prefs.search.locked?prefs.search.query:''),[searchBy,setSearchBy]=useState(prefs.search.locked?prefs.search.field:'name'),[locked,setLocked]=useState(!!prefs.search.locked);
 const [dialog,setDialog]=useState(''),[form,setForm]=useState<any>({}),[saving,setSaving]=useState(false);
 const folders:Row[]=prefs.folders;
 const favorite=(f:Row)=>prefs.files[f.id]?.favorite??f.createdBy===me.id;
 const pinned=(f:Row)=>!!prefs.files[f.id]?.pinned;
 const folderId=(f:Row)=>prefs.files[f.id]?.folderId??'';
 const updated=(f:Row)=>items.filter(i=>i.fileId===f.id).reduce((latest,i)=>[latest,i.updatedAt||i.createdAt].sort().pop(),f.updatedAt||f.createdAt||'');
 const path=(id:string):string=>{const d=folders.find(x=>x.id===id);return d?(d.parentId?path(d.parentId)+' / ':'')+d.name:'Unfiled'};
 const inside=(id:string,parent:string):boolean=>id===parent||!!folders.find(x=>x.id===id)?.parentId&&inside(folders.find(x=>x.id===id)!.parentId,parent);
 const matches=(f:Row)=>{const q=query.trim().toLowerCase();if(!q)return true;if(searchBy==='name')return f.name.toLowerCase().includes(q);const ids=new Set([...Object.keys(f.members),...f.steps.map((s:any)=>s.userId),...groups.filter(g=>f.groups.some((x:any)=>x.id===g.id)).flatMap(g=>g.members)]);return users.some(u=>ids.has(u.id)&&(u.name+' '+(u.username??'')).toLowerCase().includes(q))};
 const rows=files.filter(f=>f.archived===(view==='archived')&&(view!=='favorites'||favorite(f))&&(!folderMode||folder==='all'||(folder==='unfiled'?!folderId(f):inside(folderId(f),folder)))&&matches(f)).sort((a,b)=>view==='recent'?updated(b).localeCompare(updated(a))||a.name.localeCompare(b.name):Number(pinned(b))-Number(pinned(a))||a.name.localeCompare(b.name)).slice(0,view==='recent'?30:undefined);
 const selectedIds=selected.filter(id=>rows.some(f=>f.id===id));
 const organise=async(ids:string[],changes:any)=>{try{await call('workspace.organise',{ids,...changes},false);setSelected([]);setDialog('')}catch{}};
 const lockSearch=async()=>{try{await call('workspace.search',{locked:!locked,query,field:searchBy},false);setLocked(!locked)}catch{}};
 const openFolder=(row:any={})=>{setForm({name:'',parentId:folderMode&&!['all','unfiled'].includes(folder)?folder:'',...row});setDialog('folder')};
 const move=(ids:string[])=>{setForm({ids,folderId:folderMode&&!['all','unfiled'].includes(folder)?folder:''});setDialog('move')};
 function actions(ids:string[],single?:Row){return <DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline" size={single?'icon':'default'} aria-label={single?'Actions for '+single.name:'Menu'} disabled={!ids.length}>{single?<MoreHorizontal size={17}/>:<><Menu size={16}/>Menu<ChevronDown size={14}/></>}</Button></DropdownMenuTrigger><DropdownMenuContent align="start" className="min-w-56"><DropdownMenuLabel>{single?single.name:ids.length+' eFiles selected'}</DropdownMenuLabel><DropdownMenuSeparator/><DropdownMenuItem onSelect={()=>move(ids)}><FolderOpen/>Cluster to folder</DropdownMenuItem><DropdownMenuItem onSelect={()=>organise(ids,{pinned:true})}><Pin/>Pin to top</DropdownMenuItem><DropdownMenuItem onSelect={()=>organise(ids,{pinned:false})}>Cancel pin</DropdownMenuItem><DropdownMenuSeparator/><DropdownMenuItem onSelect={()=>organise(ids,{favorite:true})}><Star/>Mark as favorite</DropdownMenuItem><DropdownMenuItem onSelect={()=>organise(ids,{favorite:false})}>Remove from favorites</DropdownMenuItem></DropdownMenuContent></DropdownMenu>}
 function tree(parentId='',depth=0){return folders.filter(d=>d.parentId===parentId).map(d=>{const children=folders.some(x=>x.parentId===d.id);const count=files.filter(f=>!f.archived&&inside(folderId(f),d.id)).length;return <Collapsible defaultOpen key={d.id}><div className={'folder-entry '+(folder===d.id?'selected':'')} style={{paddingLeft:8+depth*14}}>{children?<CollapsibleTrigger asChild><button className="folder-expander" aria-label={'Expand or collapse '+d.name}><ChevronRight size={14}/></button></CollapsibleTrigger>:<span className="folder-spacer"/>}<button className="folder-choice" onClick={()=>{setFolder(d.id);setSelected([])}}><Folder size={16}/><span>{d.name}</span>{count>0&&<small>{count}</small>}</button></div>{children&&<CollapsibleContent>{tree(d.id,depth+1)}</CollapsibleContent>}</Collapsible>})}
 return <>
 <div className="pagehead file-pagehead"><div><h1>{folderMode?'eFile Folders':'eFile List'}</h1><p className="muted mt-2">{folderMode?'Organise your eFiles by function.':'Your accessible eFiles, in one list.'}</p></div><div className="actions">{folderMode&&<Button variant="outline" onClick={()=>openFolder()}><FolderPlus size={16}/>New folder</Button>}{me.actions.includes('createFile')&&<Button onClick={onNew}><Plus size={16}/>New eFile</Button>}</div></div>
 <div className={folderMode?'file-explorer':'file-explorer list-only'}>
 {folderMode&&<aside className="folder-panel"><div className="folder-panel-title">Folders</div><button className={'folder-root '+(folder==='all'?'selected':'')} onClick={()=>{setFolder('all');setSelected([])}}><FolderOpen size={17}/>All eFiles<span>{files.filter(f=>!f.archived).length}</span></button>{tree()}<button className={'folder-root '+(folder==='unfiled'?'selected':'')} onClick={()=>{setFolder('unfiled');setSelected([])}}><Folder size={16}/>Unfiled<span>{files.filter(f=>!f.archived&&!folderId(f)).length}</span></button><p className="folder-help">Folders, pins and favorites are personal. Moving an eFile does not change its access.</p></aside>}
 <section className="file-list-panel">
 <div className="list-toolbar"><div className="toolbar-control"><span className="control-caption">Menu</span>{actions(selectedIds)}</div><div className="toolbar-control filter-control"><span className="control-caption">Filter</span><Select value={view} onValueChange={v=>{setView(v);setSelected([])}}><SelectTrigger aria-label="Filter eFiles"><ListFilter size={15}/><SelectValue/></SelectTrigger><SelectContent><SelectItem value="favorites">Favorites</SelectItem><SelectItem value="all">Full list</SelectItem><SelectItem value="recent">Recently updated · 30</SelectItem><SelectItem value="archived">Archived</SelectItem></SelectContent></Select></div><div className="toolbar-control search-control"><label className="control-caption" htmlFor="efile-search">Search</label><div className="search-controls"><Select value={searchBy} onValueChange={setSearchBy} disabled={locked}><SelectTrigger aria-label="Search by" className="search-kind"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="name">eFile name</SelectItem><SelectItem value="user">User name</SelectItem></SelectContent></Select><div className="search-field"><Search size={16}/><Input id="efile-search" placeholder={searchBy==='user'?'Search user name…':'Search eFile name…'} value={query} disabled={locked} onChange={e=>{setQuery(e.target.value);setSelected([])}}/>{query&&!locked&&<button aria-label="Clear search" onClick={()=>setQuery('')}><X size={14}/></button>}</div><Button variant={locked?'secondary':'outline'} size="icon" aria-label={locked?'Unlock search':'Lock search'} aria-pressed={locked} title={locked?'Unlock saved search':'Keep this search when you return'} onClick={lockSearch}>{locked?<LockKeyhole size={16}/>:<Unlock size={16}/>}</Button></div></div></div>
 <div className="list-context"><div><strong>{folderMode?(folder==='all'?'List of eFiles':folder==='unfiled'?'Unfiled':path(folder)):view==='favorites'?'Favorite eFiles':view==='recent'?'Recently updated':'eFile List'}</strong><span>{rows.length} {rows.length===1?'eFile':'eFiles'}{selectedIds.length?' · '+selectedIds.length+' selected':''}</span></div><div className="actions">{locked&&<span className="search-locked"><LockKeyhole size={13}/>Search locked</span>}{folderMode&&folders.some(d=>d.id===folder)&&<DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" aria-label="Folder settings"><MoreHorizontal size={17}/></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onSelect={()=>openFolder(folders.find(d=>d.id===folder))}>Rename / move folder</DropdownMenuItem><DropdownMenuItem onSelect={()=>openFolder({parentId:folder})}>Add subfolder</DropdownMenuItem><DropdownMenuSeparator/><DropdownMenuItem onSelect={()=>{setForm({id:folder});setDialog('delete')}}>Remove folder</DropdownMenuItem></DropdownMenuContent></DropdownMenu>}</div></div>
 <div className="file-table"><Table><TableHeader><TableRow><TableHead className="check-cell"><Checkbox aria-label="Select all displayed eFiles" checked={rows.length>0&&selectedIds.length===rows.length?true:selectedIds.length?'indeterminate':false} onCheckedChange={v=>setSelected(v?rows.map(f=>f.id):[])}/></TableHead><TableHead>eFile name</TableHead><TableHead>Company</TableHead>{!folderMode&&<TableHead>Folder</TableHead>}<TableHead>Last updated</TableHead><TableHead>Items</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{rows.map(f=><TableRow key={f.id} data-state={selectedIds.includes(f.id)?'selected':undefined}><TableCell className="check-cell"><Checkbox aria-label={'Select '+f.name} checked={selectedIds.includes(f.id)} onCheckedChange={v=>setSelected(v?[...selected,f.id]:selected.filter(x=>x!==f.id))}/></TableCell><TableCell><button className="file-name" onClick={()=>onOpen(f)}><FileText size={20}/><span>{f.name}</span>{pinned(f)&&<Pin size={14} className="pinned-icon"/>}</button></TableCell><TableCell>{companyName(f.companyId)}</TableCell>{!folderMode&&<TableCell><span className="folder-cell">{path(folderId(f))}</span></TableCell>}<TableCell className="date-cell">{new Date(updated(f)).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'})}</TableCell><TableCell>{items.filter(i=>i.fileId===f.id).length}</TableCell><TableCell><div className="row-actions"><Button size="icon" variant="ghost" className={favorite(f)?'favorite-active':''} aria-label={(favorite(f)?'Remove favorite ':'Favorite ')+f.name} aria-pressed={favorite(f)} onClick={()=>organise([f.id],{favorite:!favorite(f)})}><Star size={17} fill={favorite(f)?'currentColor':'none'}/></Button>{actions([f.id],f)}</div></TableCell></TableRow>)}</TableBody></Table></div>
 {!rows.length&&<div className="file-empty"><FolderOpen size={34}/><h2>{query?'No matching eFiles':view==='favorites'?'No favorites yet':folderMode&&folder!=='all'?'This folder is empty':'No eFiles to display'}</h2><p>{query?'Try another name or unlock your saved search.':view==='favorites'?'Use the star beside an eFile to keep it here.':folderMode&&folder!=='all'?'Select eFiles in the full list, then choose Menu → Cluster to folder.':'Create an eFile or ask your administrator for access.'}</p>{me.actions.includes('createFile')&&!query&&view==='all'&&<Button variant="outline" onClick={onNew}><Plus size={16}/>Create eFile</Button>}</div>}
 <div className="list-footnote">{view==='recent'?'The 30 most recently created or updated eFiles, newest first.':'New eFiles are automatically added to the creator’s favorites.'}</div>
 </section></div>
 <Dialog open={!!dialog} onOpenChange={v=>{if(!v)setDialog('')}}><DialogContent><DialogHeader><DialogTitle>{dialog==='move'?'Cluster to folder':dialog==='delete'?'Remove folder':form.id?'Edit folder':'New folder'}</DialogTitle><DialogDescription>{dialog==='move'?'Organise selected eFiles in your folders.':dialog==='delete'?'eFiles remain available under Unfiled. Remove subfolders first.':'Choose a name and location for your folder.'}</DialogDescription></DialogHeader>
 {dialog==='folder'&&<form className="form" onSubmit={async e=>{e.preventDefault();setSaving(true);try{await call('folder.save',form,false);setDialog('')}catch{}finally{setSaving(false)}}}><label className="field"><span>Folder name</span><Input autoFocus required maxLength={200} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label className="field"><span>Parent folder</span><Select value={form.parentId||'root'} onValueChange={v=>setForm({...form,parentId:v==='root'?'':v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="root">Top level</SelectItem>{folders.filter(d=>!form.id||!inside(d.id,form.id)).map(d=><SelectItem key={d.id} value={d.id}>{path(d.id)}</SelectItem>)}</SelectContent></Select></label><Button disabled={saving}>Save folder</Button></form>}
 {dialog==='move'&&<form className="form" onSubmit={e=>{e.preventDefault();organise(form.ids,{folderId:form.folderId})}}><label className="field"><span>Folder for {form.ids?.length} eFiles</span><Select value={form.folderId||'unfiled'} onValueChange={v=>setForm({...form,folderId:v==='unfiled'?'':v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="unfiled">Unfiled</SelectItem>{folders.map(d=><SelectItem key={d.id} value={d.id}>{path(d.id)}</SelectItem>)}</SelectContent></Select></label><Button>Move selected eFiles</Button></form>}
 {dialog==='delete'&&<Button variant="destructive" onClick={async()=>{try{await call('folder.delete',form,false);setFolder('all');setDialog('')}catch{}}}>Remove folder</Button>}
 </DialogContent></Dialog>
 </>;
}
