import {load,save,user,session,db,cookie,password,validPassword,response,origin,throttle,cookieHeader,secret,totp,digest,equal,projection} from '@/lib/server';
import {mutate,check,find,id,now,required,text,defaults,live,admins,notify,audit,manage,type Row} from '@/lib/model';
import QRCode from 'qrcode';
export const dynamic='force-dynamic';
export async function GET(req:Request){try{const {state:s}=await load(req);const u=await user(req,s);const url=new URL(req.url),token=url.searchParams.get('invite');const inv=token?s.invites.find(x=>x.token===token&&x.active&&Date.parse(x.expires)>Date.now()&&s.companies.some(c=>c.id===x.companyId&&c.active)):null;return response({data:u?projection(s,u):null,invitation:inv?{company:find(s.companies,inv.companyId).name,token:inv.token}:null,hasOwner:false,reset:!!url.searchParams.get('reset')})}catch(e:any){return response({error:e.message},400)}}
export async function POST(req:Request){try{origin(req);check(Number(req.headers.get('content-length')??0)<100000,'Request too large.');const raw=await req.text();check(raw.length<100000);const {action:a,...b}=JSON.parse(raw);const {state:s,version}=await load(req);let u=await user(req,s);let headers:any={};let result:any={};
 if(['login','register','reset.complete'].includes(a))await throttle(req,a);
 if(a==='login'){const t=s.users.find(x=>x.username.toLowerCase()===text(b.username).toLowerCase());check(t&&t.pass&&live(s,t),'Invalid username or password.');check(equal(await password(b.password??'',t.salt),t.pass),'Invalid username or password.');if(t.totpSecret)check(await totp(t.totpSecret,text(b.code)),'Enter the current authenticator code.');return response({ok:true},200,{'Set-Cookie':await session(t)})}
 if(a==='logout'){const token=cookie(req,'aiwsp_session');if(token)await db().prepare('DELETE FROM sessions WHERE id=?').bind(await digest(token)).run();return response({ok:true},200,{'Set-Cookie':cookieHeader('signed-out')})}
 if(a==='register'){
  const inv=s.invites.find(x=>x.token===b.token&&x.active&&Date.parse(x.expires)>Date.now());check(inv,'This registration invitation has expired or was revoked.');const c=find(s.companies,inv.companyId);check(c.active,'This company is suspended.');
  const username=required(b.username,'Username').toLowerCase();check(/^[a-z0-9._-]{3,40}$/.test(username),'Use 3–40 letters, numbers, dots, hyphens or underscores.');check(!s.users.some(x=>x.username.toLowerCase()===username),'This username is already taken.');validPassword(b.password);check(b.password===b.confirm,'Passwords do not match.');const salt=id();const t={id:id(),companyId:c.id,name:required(b.name,'Full name'),username,phone:required(b.phone,'WeCom mobile number'),email:'',role:'member',level:3,permissions:{},active:true,expires:'',revision:0,salt,pass:await password(b.password,salt)};
  s.users.push(t);notify(s,admins(s,c.id),`New user registered: ${t.name}. Default permissions are active.`);audit(s,t,'Registered account',t.name,c.id);await save(s,version);return response({ok:true},200,{'Set-Cookie':await session(t)});
 }
 if(a==='reset.complete'){const hash=await digest(String(b.token));const t=s.users.find(x=>x.resetHash===hash&&Date.parse(x.resetExpires)>Date.now());check(t,'This reset link has expired.');validPassword(b.password);check(b.password===b.confirm,'Passwords do not match.');if(t.totpSecret)check(await totp(t.totpSecret,text(b.code)),'Enter the current authenticator code.');t.salt=id();t.pass=await password(b.password,t.salt);t.revision++;delete t.resetHash;delete t.resetExpires;audit(s,t,'Reset password',t.name,t.companyId);await save(s,version);return response({ok:true},200,{'Set-Cookie':await session(t)})}
 check(u,'Please sign in.');u=u!;
 if(a==='account.save'){u.name=required(b.name);if(b.password){validPassword(b.password);check(b.password===b.confirm,'Passwords do not match.');if(u.pass)check(equal(await password(b.currentPassword??'',u.salt),u.pass),'Current password is incorrect.');u.salt=id();u.pass=await password(b.password,u.salt);u.revision++;headers['Set-Cookie']=await session(u)}audit(s,u,'Updated account',u.name,u.companyId)}
 else if(a==='mfa.setup'){const sec=secret();u.pendingTotp=sec;result={secret:sec,qr:await QRCode.toDataURL(`otpauth://totp/AiWSP:${encodeURIComponent(u.username)}?secret=${sec}&issuer=AiWSP`)}}
 else if(a==='mfa.enable'){check(u.pendingTotp&&await totp(u.pendingTotp,text(b.code)),'Enter the code from your authenticator app.');u.totpSecret=u.pendingTotp;delete u.pendingTotp;audit(s,u,'Enabled authenticator',u.name,u.companyId)}
 else if(a==='reset.create'){const t=find(s.users,b.id);check(manage(s,u,t.companyId)&&t.role!=='system','Use Account settings for a System Admin password.');const token=id()+id();t.resetHash=await digest(token);t.resetExpires=new Date(Date.now()+3600000).toISOString();result={token};audit(s,u,'Created password reset',t.name,t.companyId)}
 else if(a==='invite.qr'){const inv=find(s.invites,b.id);check(manage(s,u,inv.companyId));return response({result:{qr:await QRCode.toDataURL(new URL('/?invite='+inv.token,req.url).href)}})}
 else result=mutate(s,u,a,b);
 await save(s,version);return response({result,data:projection(s,u)},200,headers);
 }catch(e:any){return response({error:e.message??'Unable to save changes.'},400)}}
